baseURL = "https://idmitryz.github.io"
title = "idmitryz"
languageCode = "en"
defaultContentLanguage = "en"
theme = "zozo"
summaryLength = 100
paginate = 4

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[params]
  description = "Bliki"
  copyright = "Copyright © 2020 Glubokov Dmitry"
  highlight = true
  footerSlogan = "Мир | Труд | Дружба"
  keywords = ["idmitryz","glubokov","biotech", "blog"]
  enableMathJax = true
  enableSummary = true   

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 10
  [[menu.main]]  
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 20
  [[menu.main]]
    identifier = "bliki"
    name = "bliki"
    title = "bliki"
    url = "/bliki/"
    weight = 30  

[social]
  github = "https://github.com/idmitryz"
  stack-overflow = "https://habr.com/ru/users/lamplampov/"
  linkedin = "https://habr.com/ru/users/lamplampov/"
  instagram = "https://habr.com/ru/users/lamplampov/"
  telegram = "https://habr.com/ru/users/lamplampov/"
