baseURL = "https://dmtgk.github.io"
title = "dmtgk"
languageCode = "en"
defaultContentLanguage = "en"
theme = "zozo"
summaryLength = 50
paginate = 10

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[params]
  description = "Bliki"
  copyright = "Copyright © 2020 Glubokov Dmitry"
  highlight = true
  footerSlogan = "Мир | Труд | Дружба"
  keywords = ["idmitryz","glubokov","biotech", "blog"]
  enableMathJax = true
  enableSummary = true
  mainSections = ["posts","post"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 10
  [[menu.main]]  
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 20
  [[menu.main]]
    identifier = "bliki"
    name = "bliki"
    title = "bliki"
    url = "/bliki/"
    weight = 30

  [[menu.main]]
    name = "tags"
    weight = 40
    identifier = "tags"
    url = "/tags/"

[social]
  github = "https://github.com/dmtgk"
  stack-overflow = "https://stackoverflow.com/users/11982188/glubokov"
  linkedin = "https://www.linkedin.com/in/dmitry-glubokov-aa38311a6/"
  instagram = "https://www.instagram.com/dmitrydeliberate/"
  telegram = "https://t.me/dmtgk"
